### ISSUE TITLE
error running ./kisstatic2mobile.py

### ISSUE THREAD

**Issue by ro0TuX777** [ckoval7/kisStatic2Mobile#1]
When attempting to run the command: ./kisstatic2mobile.py --send xxx.xxx.xxx.xxx:3501 
error message: 
File "./kisstatic2mobile.py", line 77
   s_print(f"Passing {len(data)} Bytes")
                                                             ^
SyntaxError: invalid syntax

**Comment by ckoval7** [comment]
What version of python are you running?

**Comment by ckoval7** [comment]
I've preemptively added python version enforcement, please try the latest commit.

**Comment by ro0TuX777** [comment]
Thanks for the response, when I run the command: python -V
the result is Python 3.9.7

**Comment by ckoval7** [comment]
I've set up Python 3.9.7 on Ubuntu 21.10 and am unable to reproduce the error. Are you able to provide more information about your setup?
